export const GET_DATA = 'GET_DATA';
export const SET_DATE_FILTER_FORMAT = 'SET_DATE_FILTER_FORMAT';
export const SET_ASYLUM_OFFICE_FILTER = 'SET_ASYLUM_OFFICE_FILTER';
export const SET_REGION_FILTER = 'SET_REGION_FILTER';
