export const GET_DATA = 'GET_DATA';
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const FILTER_SEARCH = 'FILTER_SEARCH';
export const FILTER_CATEGORIES = 'FILTER_CATEGORIES';
export const RESET_FILTER = 'RESET_FILTER';
