export const GET_DATA = 'GET_DATA';
export const FILTER_SEARCH = 'FILTER_SEARCH';
export const RESET_DATA = 'RESET_DATA';

//Backend filter & fetch actions
export const GET_FILTERED_DATA = 'GET_FILTERED_DATA';
export const GET_DEFAULT_COMPARISONS = 'GET_DEFAULT_COMPARISONS';
export const SET_DATE_FILTER_FORMAT = 'SET_DATE_FILTER_FORMAT';
export const SET_ASYLUM_OFFICE_FILTER = 'SET_ASYLUM_OFFICE_FILTER';
export const SET_CONTINENT_FILTER = 'SET_CONTINENT_FILTER';
